yaplist/playlist/urls.py
from django.urls import path

from yaplist.playlist import views as playlist_views


app_name = 'playlist'

urlpatterns = [
    path('new/', playlist_views.create, name='create'),
    path('edit/<int:playlist_id>/', playlist_views.edit, name='edit'),
    path('delete/<int:playlist_id>/', playlist_views.delete, name='delete'),
    path('play/<int:playlist_id>/', playlist_views.playlist, name='playlist'),
]

yaplist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from yaplist.core import views as core_views

admin.autodiscover()

urlpatterns = [
    url(r'^dashboard/$', core_views.dashboard, name='dashboard'),

    url(r'^admin/', admin.site.urls),
    url(r'^', include(('yaplist.playlist.urls', 'playlist'))),
    url(r'^', include(('yaplist.user_accounts.urls', 'user_accounts'))),

    url(r'^$', core_views.home, name='home'),
]

yaplist/user_accounts/urls.py
from django.urls import path

from yaplist.user_accounts import views as user_accounts_views


app_name = 'user_accounts'

urlpatterns = [
    path('signin/', user_accounts_views.signin, name='signin'),
    path('signout/', user_accounts_views.signout, name='signout'),
    path('signup/', user_accounts_views.signup, name='signup'),
]

yaplist/core/models.py
from django.db import models

# Create your models here.

yaplist/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User

def home(request):
    if request.user.is_authenticated:
        return render(request, 'core/cover.html', {
             'logged_in': True,
             'user': request.user,
            }) # Template will show a Dashboard redirect button
    else:
        return render(request, 'core/cover.html')

def dashboard(request):
    user = get_object_or_404(User, username=request.user)
    if request.user.is_authenticated:
        user_playlists = request.user.profile.get_playlists()
        return render(request, 'core/dashboard.html', {
             'user_playlists': user_playlists,
             'user': user,
            })
    else:
        return redirect('/signin/')

yaplist/core/templates/core/cover.html
{% extends 'base.html' %}

{% block title %}Yaplist{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-2">Keep On Playing!</h1>
    <p class="lead">Collect your favourite Youtube videos in one place</p>
    <p><a class="btn btn-lg btn-success" href="{% url 'user_accounts:signup' %}" role="button">Sign Up</a></p>
  </div>

  <div class="row marketing">
    <div class="col-md-3">
      <i class="fas fa-asterisk fa-7x"></i>
    </div>
    <div class="col-md-9">
      <h4>Create</h4>
      <p>Create and store collections of your favourite Youtube videos effortlessly!</p>
    </div>
  </div>
  <div class="row marketing">
    <div class="col-md-9">
      <h4>Manage</h4>
      <p>View and edit all your collections conveniently in one place.</p>
    </div>
    <div class="col-md-3">
      <i class="fas fa-bolt fa-7x"></i>
    </div>
  </div>
{% endblock %}

yaplist/core/templates/core/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard - Yaplist{% endblock %}

{% block content %}
<div class="text-center"> 
  <a role="button" href="{% url 'dashboard' %}" class="btn btn-secondary">View Playlists</a>
  <a role="button" href="{% url 'playlist:create' %}" class="btn btn-secondary">Add Playlist</a>
</div>

<div class="row marketing">
  <div class="col-md-12">
    <ul id="playlist-list-group" class="list-group">
      {% for playlist in user_playlists %}
        <li class="list-group-item">
          <a href="{% url 'playlist:playlist' playlist.id %}">
            <span class="far fa-play-circle fa-4x" style=" vertical-align: middle;"></span>
          </a>
          <span>
            {{ playlist.title|truncatechars:60 }}
          </span>
          <span class="badge badge-primary">
            {{ playlist.item_set.all|length }} Videos
          </span>
          <form class="form-horizontal float-right" method="post" action="{% url 'playlist:delete' playlist.id %}">
            {% csrf_token %}
            <div class="control-group">
                <div class="controls">
                  <a href={% url 'playlist:edit' playlist.id %}>
                    <button type="button" class="btn btn-outline-primary btn-sm">
                      Edit
                    </button>
                  </a>
                  <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                </div>
            </div>
          </form>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock content %}